
FROM node:16-alpine 
# Set the working directory to /app inside the container

WORKDIR /app
COPY . .

# ==== BUILD =====

RUN npm ci 
RUN npm run build

# ==== RUN =======

EXPOSE 3000

CMD [ "npx", "serve", "build" ]