FROM python:3.9

COPY ./requirements.txt /requirements.txt

RUN pip install --upgrade -r requirements.txt

COPY . ./backend

WORKDIR ./backend

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
